apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gcp-marketplace-cloudbees-com
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gcp-marketplace.cloudbees.com
  dnsNames:
    - gcp-marketplace.cloudbees.com
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - gcp-marketplace.cloudbees.com