apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    partition: cloud-bill-saas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: gcr.io/cloud-bill-dev/frontend-service:latest
          env:
            #            - name: CLOUD_BILL_FRONTEND_SERVICE_ENDPOINT
            #              value: "8086"
            #            - name: CLOUD_BILL_FRONTEND_HEALTH_CHECK_ENDPOINT
            #              value: "8096"
            #            - name: CLOUD_BILL_SUBSCRIPTION_SERVICE_URL
            #              value: "http://subscription-service.default.svc.cluster.local:8085/api/v1"
            #            - name: CLOUD_BILL_FRONTEND_CLIENT_ID
            #              value: "<yourauth0clientid>"
            #            - name: CLOUD_BILL_FRONTEND_CLIENT_SECRET
            #              value: "<yourauth0clientsecret>"
            #            - name: CLOUD_BILL_FRONTEND_CALLBACK_URL
            #              value: "https://<yourhost>/callback"
            #            - name: CLOUD_BILL_FRONTEND_ISSUER
            #              value: "https://<yourdomain/>"
            #            - name: CLOUD_BILL_FRONTEND_SESSION_KEY
            #              value: "<yoursessionkey>"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /auth/gcp-service-account/gcp-service-account.json
            - name: CLOUD_BILL_FRONTEND_CONFIG_FILE
              value: /auth/frontend-service-config/frontend-service-config.json
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: gcp-service-account
              mountPath: "/auth/gcp-service-account"
              readOnly: true
            - name: frontend-service-config
              mountPath: "/auth/frontend-service-config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account
        - name: frontend-service-config
          secret:
            secretName: frontend-service-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  labels:
    app: subscription-service
    partition: cloud-bill-saas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: gcr.io/cloud-bill-dev/subscription-service:latest
          env:
            #            - name: CLOUD_BILL_SUBSCRIPTION_SERVICE_ENDPOINT
            #              value: "8085"
            #            - name: CLOUD_BILL_SUBSCRIPTION_HEALTH_CHECK_ENDPOINT
            #              value: "8095"
            #            - name: CLOUD_BILL_SUBSCRIPTION_CLOUD_COMMERCE_PROCUREMENT_URL
            #              value: "https://cloudcommerceprocurement.googleapis.com/"
            #            - name: CLOUD_BILL_SUBSCRIPTION_PARTNER_ID
            #              value: "<yourpartnerid>"
            #            - name: CLOUD_BILL_SUBSCRIPTION_GCP_PROJECT_ID
            #              value: "<yourprojectid>"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /auth/gcp-service-account/gcp-service-account.json
            - name: CLOUD_BILL_SUBSCRIPTION_CONFIG_FILE
              value: /auth/subscription-service-config/subscription-service-config.json
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: gcp-service-account
              mountPath: "/auth/gcp-service-account"
              readOnly: true
            - name: subscription-service-config
              mountPath: "/auth/subscription-service-config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8095
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8095
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account
        - name: subscription-service-config
          secret:
            secretName: subscription-service-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-service
  labels:
    app: pubsub-service
    partition: cloud-bill-saas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-service
  template:
    metadata:
      labels:
        app: pubsub-service
    spec:
      containers:
        - name: pubsub-service
          image: gcr.io/cloud-bill-dev/pubsub-service:latest
          env:
            #            - name: CLOUD_BILL_PUBSUB_SERVICE_ENDPOINT
            #              value: "8087"
            #            - name: CLOUD_BILL_PUBSUB_HEALTH_CHECK_ENDPOINT
            #              value: "8097"
            #            - name: CLOUD_BILL_PUBSUB_SUBSCRIPTION
            #              value: "codelab"
            #            - name: CLOUD_BILL_PUBSUB_TOPIC_PREFIX
            #              value: "DEMO-"
            #            - name: CLOUD_BILL_SUBSCRIPTION_SERVICE_URL
            #              value: "https://subscription-service.cloudbees-jenkins-support.svc.cluster.local"
            #            - name: CLOUD_BILL_PUBSUB_CLOUD_COMMERCE_PROCUREMENT_URL
            #              value: "https://cloudcommerceprocurement.googleapis.com/"
            #            - name: CLOUD_BILL_PUBSUB_PARTNER_ID
            #              value: "<yourpartnerid>"
            #            - name: CLOUD_BILL_PUBSUB_GCP_PROJECT_ID
            #              value: "<yourprojectid>"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /auth/gcp-service-account/gcp-service-account.json
            - name: CLOUD_BILL_PUBSUB_CONFIG_FILE
              value: /auth/pubsub-service-config/pubsub-service-config.json
          volumeMounts:
            - name: gcp-service-account
              mountPath: "/auth/gcp-service-account"
              readOnly: true
            - name: pubsub-service-config
              mountPath: "/auth/pubsub-service-config"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8097
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8097
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account
        - name: pubsub-service-config
          secret:
            secretName: pubsub-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - port: 8086
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
spec:
  selector:
    app: subscription-service
  ports:
    - port: 8085
      name: http
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datastore-backup
  labels:
    app: datastore-backup
    partition: cloud-bill-cron-job
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datastore-backup
              image: gcr.io/cloud-bill-dev/datastore-backup:latest
              env:
                #            - name: CLOUD_BILL_DATASTORE_BACKUP_GCS_BUCKET
                #              value: "gs://bucket"
                #            - name: CLOUD_BILL_DATASTORE_BACKUP_GCP_PROJECT_ID
                #              value: "<yourprojectid>"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /auth/gcp-service-account/gcp-service-account.json
                - name: CLOUD_BILL_DATASTORE_BACKUP_CONFIG_FILE
                  value: /auth/datastore-backup-config/datastore-backup-config.json
              volumeMounts:
                - name: gcp-service-account
                  mountPath: "/auth/gcp-service-account"
                  readOnly: true
                - name: datastore-backup-config
                  mountPath: "/auth/datastore-backup-config"
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: gcp-service-account
              secret:
                secretName: gcp-service-account
            - name: datastore-backup-config
              secret:
                secretName: datastore-backup-config