apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cloudbees-jenkins-support-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: subscription-frontend
spec:
  hosts:
    - "*"
  gateways:
    - cloudbees-jenkins-support-gateway
  http:
  - route:
      - destination:
          port:
            number: 8086
          host: frontend-service