apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jfry@cloudbees.com
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
          accessKeyID: AKIA6F5YXFD46KUTEFGM
          secretAccessKeySecretRef:
            name: aws-cloudbees-iam
            key: secret-access-key