basePath: /api/v1
definitions:
  persistence.Account:
    properties:
      approvals:
        items:
          $ref: '#/definitions/persistence.Approval'
        type: array
      createTime:
        type: string
      name:
        type: string
      provider:
        type: string
      state:
        type: string
      updateTime:
        type: string
    type: object
  persistence.Approval:
    properties:
      name:
        type: string
      reason:
        type: string
      state:
        type: string
      updateTime:
        type: string
    type: object
  persistence.Contact:
    properties:
      accountName:
        type: string
      company:
        type: string
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      timezone:
        type: string
    type: object
  persistence.Entitlement:
    properties:
      account:
        type: string
      createTime:
        type: string
      messageToUser:
        type: string
      name:
        type: string
      newPendingPlan:
        type: string
      plan:
        type: string
      product:
        type: string
      provider:
        type: string
      state:
        type: string
      updateTime:
        type: string
      usageReportingId:
        type: string
    type: object
host: localhost:8085
info:
  contact:
    email: support@cloudbees.com
    name: CloudBees Support
    url: http://support.cloudbees.com
  license: {}
  termsOfService: https://www.cloudbees.com/products/terms-service
paths:
  /accounts:
    put:
      consumes:
      - application/json
      description: Upsert an account passing account json
      operationId: cloud-bill-saas-subscription-service-upsert-account
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/persistence.Account'
          type: object
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert an account
  /accounts/{accountName}:
    delete:
      consumes:
      - application/json
      description: Delete an account
      operationId: cloud-bill-saas-subscription-service-delete-account
      parameters:
      - description: Account Name
        in: path
        name: accountName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing account name in path
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete an account
    get:
      consumes:
      - application/json
      description: Retrieves an account by account name
      operationId: cloud-bill-saas-subscription-service-get-account
      parameters:
      - description: Account Name
        in: path
        name: accountName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Account'
        "400":
          description: Missing account name in path
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get an account
  /contacts:
    put:
      consumes:
      - application/json
      description: Upsert an contact passing contact json
      operationId: cloud-bill-saas-subscription-service-upsert-contact
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert an contact
  /contacts/{accountName}:
    delete:
      consumes:
      - application/json
      description: Delete an contact
      operationId: cloud-bill-saas-subscription-service-delete-contact
      parameters:
      - description: Account Name
        in: path
        name: accountName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing account name in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete an contact
    get:
      consumes:
      - application/json
      description: Retrieves an contact by account name
      operationId: cloud-bill-saas-subscription-service-get-contact
      parameters:
      - description: Account Name
        in: path
        name: accountName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Contact'
        "400":
          description: Missing account name in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get an contact
  /entitlements:
    put:
      consumes:
      - application/json
      description: Upsert an entitlement passing entitlement json
      operationId: cloud-bill-saas-subscription-service-upsert-entitlement
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert an entitlement
  /entitlements/{entitlementName}:
    delete:
      consumes:
      - application/json
      description: Delete an entitlement
      operationId: cloud-bill-saas-subscription-service-delete-entitlement
      parameters:
      - description: Entitlement Name
        in: path
        name: entitlementName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing entitlement name in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete an entitlement
    get:
      consumes:
      - application/json
      description: Retrieves an entitlement by entitlement name
      operationId: cloud-bill-saas-subscription-service-get-entitlement
      parameters:
      - description: Entitlement Name
        in: path
        name: entitlementName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Entitlement'
        "400":
          description: Missing entitlement name in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get an entitlement
swagger: "2.0"
