basePath: /api/v1
definitions:
  persistence.Account:
    properties:
      approvals:
        items:
          $ref: '#/definitions/persistence.Approval'
        type: array
      createTime:
        type: string
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      state:
        type: string
      updateTime:
        type: string
    type: object
  persistence.Approval:
    properties:
      name:
        type: string
      reason:
        type: string
      state:
        type: string
      updateTime:
        type: string
    type: object
  persistence.Contact:
    properties:
      accountId:
        type: string
      company:
        type: string
      emailAddress:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      timezone:
        type: string
    type: object
  persistence.Entitlement:
    properties:
      account:
        type: string
      createTime:
        type: string
      id:
        type: string
      messageToUser:
        type: string
      name:
        type: string
      newPendingPlan:
        type: string
      plan:
        type: string
      product:
        type: string
      provider:
        type: string
      state:
        type: string
      updateTime:
        type: string
      usageReportingId:
        type: string
    type: object
host: localhost:8085
info:
  contact:
    email: support@cloudbees.com
    name: CloudBees Support
    url: http://support.cloudbees.com
  license: {}
  termsOfService: https://www.cloudbees.com/products/terms-service
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: Gets an array of accounts
      operationId: cloud-bill-saas-subscription-service-get-accounts
      parameters:
      - description: optional comma separated list of filter
        in: query
        name: filters
        type: string
      - description: optional order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/persistence.Account'
            type: array
        "500":
          description: Error
          schema:
            type: string
      summary: GetAccounts
    put:
      consumes:
      - application/json
      description: Upsert an account passing account json
      operationId: cloud-bill-saas-subscription-service-upsert-account
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/persistence.Account'
          type: object
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert an account
  /accounts/{accountId}:
    delete:
      consumes:
      - application/json
      description: Delete an account
      operationId: cloud-bill-saas-subscription-service-delete-account
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing account ID in path
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete an account
    get:
      consumes:
      - application/json
      description: Retrieves an account by account ID
      operationId: cloud-bill-saas-subscription-service-get-account
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Account'
        "400":
          description: Missing account ID in path
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get an account
  /accounts/{accountId}/entitlements:
    get:
      consumes:
      - application/json
      description: Gets an array of entitlements for an account
      operationId: cloud-bill-saas-subscription-service-get-account-entitlements
      parameters:
      - description: account
        in: path
        name: acct
        required: true
        type: string
      - description: optional comma separated list of filter
        in: query
        name: filters
        type: string
      - description: optional order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/persistence.Entitlement'
            type: array
        "500":
          description: Error
          schema:
            type: string
      summary: GetAccountEntitlements
  /contacts:
    get:
      consumes:
      - application/json
      description: Gets an array of contacts
      operationId: cloud-bill-saas-subscription-service-get-contacts
      parameters:
      - description: optional comma separated list of filter
        in: query
        name: filters
        type: string
      - description: optional order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/persistence.Contact'
            type: array
        "500":
          description: Error
          schema:
            type: string
      summary: GetContacts
    put:
      consumes:
      - application/json
      description: Upsert a contact passing contact json
      operationId: cloud-bill-saas-subscription-service-upsert-contact
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert a contact
  /contacts/{accountId}:
    delete:
      consumes:
      - application/json
      description: Delete an contact
      operationId: cloud-bill-saas-subscription-service-delete-contact
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing account ID in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete an contact
    get:
      consumes:
      - application/json
      description: Retrieves an contact by account ID
      operationId: cloud-bill-saas-subscription-service-get-contact
      parameters:
      - description: Account ID
        in: path
        name: accountId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Contact'
        "400":
          description: Missing account ID in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get an contact
  /entitlements:
    get:
      consumes:
      - application/json
      description: Gets an array of entitlements
      operationId: cloud-bill-saas-subscription-service-get-entitlements
      parameters:
      - description: optional comma separated list of filter
        in: query
        name: filters
        type: string
      - description: optional order
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/persistence.Entitlement'
            type: array
        "500":
          description: Error
          schema:
            type: string
      summary: GetEntitlements
    put:
      consumes:
      - application/json
      description: Upsert an entitlement passing entitlement json
      operationId: cloud-bill-saas-subscription-service-upsert-entitlement
      produces:
      - application/json
      responses:
        "204":
          description: Upserted
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Upsert an entitlement
  /entitlements/{entitlementId}:
    delete:
      consumes:
      - application/json
      description: Delete an entitlement
      operationId: cloud-bill-saas-subscription-service-delete-entitlement
      parameters:
      - description: Entitlement ID
        in: path
        name: entitlementId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deleted
          schema:
            type: string
        "400":
          description: Missing entitlement ID in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Delete an entitlement
    get:
      consumes:
      - application/json
      description: Retrieves an entitlement by entitlement ID
      operationId: cloud-bill-saas-subscription-service-get-entitlement
      parameters:
      - description: Entitlement ID
        in: path
        name: entitlementId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/persistence.Entitlement'
        "400":
          description: Missing entitlement ID in path
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Get an entitlement
  /healthz:
    get:
      consumes:
      - application/json
      description: Check the health of the subscription service
      operationId: cloud-bill-saas-subscription-service-healthz
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            type: string
        "500":
          description: Error
          schema:
            type: string
      summary: Check the health of the subscription service
swagger: "2.0"
